name: Push and test

on: 
  push:
    branches:
      - development
      - main

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    #strategy:
    #  matrix:
    #    python-version: [3.7, 3.8, 3.9, 3.10, 3.11]
    env:
      IS_BETA: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      #  with:
      #    python-version: '3.x'
      - name: Generate documentation
        run: |
          sh scripts/mkdoc.sh
      - name: Run tests
        run: |
          sh scripts/mktest.sh
      - name: Test check
        run: |
          echo ${{ env.IS_BETA }}

      - run: pip install ruff
      - run: | 
          ruff check .
          ruff fix .
    outputs:
      deploy-on-main: ${{ env.IS_BETA }}
  
  deploy-main:
    runs-on: ubuntu-latest
    if: needs.deploy-main.build.outputs == false 
    steps:
      - uses: actions/checkout@v4
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'style fixes by ruff'
          branch: mains
