name: Push and test

on: [push]

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IS_BETA: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Generate documentation
        run: |
          sh scripts/mkdoc.sh
      - name: Run tests
        run: |
          sh scripts/mktest.sh
      - name: Test check
        run: |
          echo ${{ env.IS_BETA }}
      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff check --output-format=github .
          continue-on-error: false